BookRegistrationSystem/Controllers/AuthorController.cs
using BookRegistrationSystem.Data;
using BookRegistrationSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Controllers
{
    public class AuthorController : Controller
    {
        private readonly BookDbContext _bookDbContext;

        public AuthorController(BookDbContext bookDbContext)
        {
            _bookDbContext = bookDbContext;
           
        }
        public IActionResult Index()
        {
           var listItems = _bookDbContext.Authors.ToList();
            return View(listItems);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Author author = new Author();

            return View(author);
        }
        [HttpPost]
        public IActionResult Create(Author author)
        {
            _bookDbContext.Authors.Add(author);
            _bookDbContext.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id != null)
            {
                Author author = _bookDbContext.Authors.Find(id);
                return View(author);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Update(Author author)
        {
                _bookDbContext.Authors.Update(author);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                Author author = _bookDbContext.Authors.Find(id);
                return View(author);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(Author author)
        {
            if (ModelState.IsValid)
            {
                _bookDbContext.Authors.Remove(author);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }
    }
}

BookRegistrationSystem/Controllers/BookAuthorsController.cs
using BookRegistrationSystem.Data;
using BookRegistrationSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Controllers
{
    public class BookAuthorsController : Controller
    {
        private readonly BookDbContext _bookDbContext;

        public BookAuthorsController(BookDbContext bookDbContext)
        {  
            _bookDbContext = bookDbContext;
        }

        public IActionResult Index()
        {
            var listItems = _bookDbContext.BookAuthorss.ToList();
            return View(listItems);
        }
        [HttpGet]
        public IActionResult Create()
        {
            BookAuthors bookAuthors = new BookAuthors();

            return View(bookAuthors);
        }
        [HttpPost]
        public IActionResult Create(BookAuthors bookAuthors)
        {
                _bookDbContext.BookAuthorss.Add(bookAuthors);
                _bookDbContext.SaveChanges();
                TempData["SuccesMesssage"] = "BookAuthors added succecfully";
                return RedirectToAction("Index");
            }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id != null)
            {
                BookAuthors bookAuthors = _bookDbContext.BookAuthorss.Find(id);
                return View(bookAuthors);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Update(BookAuthors bookAuthors)
        {
                _bookDbContext.BookAuthorss.Update(bookAuthors);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                BookAuthors bookAuthors = _bookDbContext.BookAuthorss.Find(id);
                return View(bookAuthors);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(BookAuthors bookAuthors)
        {
            if (ModelState.IsValid)
            {
                _bookDbContext.BookAuthorss.Remove(bookAuthors);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookAuthors);
        }
    }
}

BookRegistrationSystem/Controllers/BookController.cs
using BookRegistrationSystem.Data;
using BookRegistrationSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Controllers
{
    public class BookController : Controller
    {
        private readonly BookDbContext _bookDbContext;

        public BookController(BookDbContext bookDbContext)
        {
            _bookDbContext = bookDbContext;
        }

        public IActionResult Index()
        {
            var listItems = _bookDbContext.Books.Include(c=> c.Category).Include(c => c.Author).Include(c => c.Publisher).ToList();
            return View(listItems);
        }
        [HttpGet]
        public IActionResult Create()
        {

            ViewBag.Category = new SelectList(_bookDbContext.BookCategorys.ToList(), "Id", "Name");
            ViewBag.Author = new SelectList(_bookDbContext.Authors.ToList(), "Id", "Name");
            ViewBag.Pulisher = new SelectList(_bookDbContext.Publishers.ToList(), "Id", "Name");
            return View();
        }
        [HttpPost]
        public IActionResult Createold(Book book)
        {
           

            return View(book);
        }
        [HttpPost]
        public IActionResult Create(Book book)
        {
                _bookDbContext.Books.Add(book);
                _bookDbContext.SaveChanges();
                TempData["SuccesMesssage"] = "Book added succecfully";
                return RedirectToAction("Index");
            }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id != null)
            {
                ViewBag.Publisher = new SelectList(_bookDbContext.Publishers.ToList(), "Id", "Name");
                ViewBag.BookCategory = new SelectList(_bookDbContext.BookCategorys.ToList(), "Id", "Name");
                ViewBag.Author = new SelectList(_bookDbContext.Authors.ToList(), "Id", "Name");
                var book = _bookDbContext.Books.Find(id);
                return View(book);
            }
            return View();
        }
        [HttpPost]
        public IActionResult Update(Book book)
        {
                _bookDbContext.Books.Update(book);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                Book book = _bookDbContext.Books.Find(id);
                return View(book);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(Book book)
        {
            if (ModelState.IsValid)
            {
                _bookDbContext.Books.Remove(book);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(book);
        }
    }
}

BookRegistrationSystem/Controllers/PublisherController.cs
using BookRegistrationSystem.Data;
using BookRegistrationSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Controllers
{
    public class PublisherController : Controller
    {
        private readonly BookDbContext _bookDbContext;

        public PublisherController(BookDbContext bookDbContext)
        {
            _bookDbContext = bookDbContext;
       }

        public IActionResult Index()
        {
            var listItems = _bookDbContext.Publishers.ToList();
            return View(listItems);
        }
        [HttpGet]
        public IActionResult Create()
        {
            Publisher publisher = new Publisher();

            return View(publisher);
        }
        [HttpPost]
        public IActionResult Createold(Publisher publisher)
        {
            _bookDbContext.Publishers.Add(publisher);
            _bookDbContext.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpPost]
        public IActionResult Create(Publisher publisher)
        {
                _bookDbContext.Publishers.Add(publisher);
                _bookDbContext.SaveChanges();
                TempData["SuccesMesssage"] = "Publisher added succecfully";
                return RedirectToAction("Index");
            }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id != null)
            {
                Publisher publisher = _bookDbContext.Publishers.Find(id);
                return View(publisher);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Update(Publisher publisher)
        {
               _bookDbContext.Publishers.Update(publisher);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                Publisher publisher = _bookDbContext.Publishers.Find(id);
                return View(publisher);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _bookDbContext.Publishers.Remove(publisher);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(publisher);
        }
    }
}

BookRegistrationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookRegistrationSystem</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/dashboard/">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/assets/dashboard/template.css" rel="stylesheet" />
    <link href="~/assets/dashboard/dashboard.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">P514</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-2">
                @Html.Partial("_SidebarMenu")
            </div>
            <div class="col-10">
                <div class="container-fluid">

                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - P514 
        </div>
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>

    <script src="~/assets/dashboard/dashboard.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookRegistrationSystem/Views/Shared/_ShowResult.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

BookRegistrationSystem/Views/Shared/_SidebarMenu.cshtml
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" asp-area="" asp-controller="Book" asp-action="Index">
                    Book
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Author" asp-action="Index">
                    Author
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="BookAuthors" asp-action="Index">
                    Book Authors
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="BookCategory" asp-action="Index">
                    Book Category
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="AuthorContact" asp-action="Index">
                    Author Contact
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Publisher" asp-action="Index">
                    Publisher
                </a>
            </li>
        </ul>
    </div>
</nav>