BookRegistrationSystem/Models/BookCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Models
{
    public class BookCategory :Base
    {
        [Required]
        [DisplayName("Kitab növü")]
        public string Name { get; set; }
      
    }
}

BookRegistrationSystem/Controllers/BookCategoryController.cs
using BookRegistrationSystem.Data;
using BookRegistrationSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Controllers
{
    public class BookCategoryController : Controller
    {
        private readonly BookDbContext _bookDbContext;
 
        public BookCategoryController(BookDbContext bookDbContext)
        {
            _bookDbContext = bookDbContext;
        }

        public IActionResult Index()
        {
            var listItems = _bookDbContext.BookCategorys.ToList();
            return View(listItems);
        }
        [HttpGet]
        public IActionResult Create()
        {
            BookCategory bookCategory = new BookCategory();

            return View(bookCategory);
        }
        [HttpPost]
        public IActionResult Create(BookCategory bookCategory)
        {
            _bookDbContext.BookCategorys.Add(bookCategory);
            _bookDbContext.SaveChanges();
            TempData["SuccesMesssage"] = "BookCategory added succecfully";
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id != null)
            {
               BookCategory bookCategory = _bookDbContext.BookCategorys.Find(id);
                return View(bookCategory);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Update(BookCategory bookCategory)
        {
            _bookDbContext.BookCategorys.Update(bookCategory);
            _bookDbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                BookCategory bookCategory = _bookDbContext.BookCategorys.Find(id);
                return View(bookCategory);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(BookCategory bookCategory)
        {
            if (ModelState.IsValid)
            {
                _bookDbContext.BookCategorys.Remove(bookCategory);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bookCategory);
        }
    }
}

BookRegistrationSystem/Views/BookCategory/Create.cshtml
@model BookCategory
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="container mt-5">
    <form method="post" asp-action="create" enctype="multipart/form-data">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mt-3 text-end">
                <a class="btn btn-info" asp-area="" asp-controller="BookCategory" asp-action="Index"><i class="bi bi-arrow-return-left"></i> Back to main</a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </form>

</div>

BookRegistrationSystem/Views/BookCategory/Delete.cshtml
@model BookCategory
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div class="container mt-5">
    <form method="post" asp-action="delete" enctype="multipart/form-data">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mt-3 text-end">
                <a class="btn btn-info" asp-area="" asp-controller="BookCategory" asp-action="Index"><i class="bi bi-arrow-return-left"></i> Back to main</a>
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>

</div>

BookRegistrationSystem/Views/BookCategory/Index.cshtml
@model List<BookCategory>
@{
    ViewData["Title"] = "Index";
}

<partial name="_ShowResult" />

<div class="page-container mt-5">
    <div class="row">
        <div class="col-6 text-end">
            <a class=" text-dark btn btn-success" asp-area="" asp-controller="BookCategory" asp-action="Create">Create Book Category</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-hover table-bordered table-striped mt-5">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Name</td>
                        <td>
                            <a class=" text-dark btn btn-warning" asp-area="" asp-controller="BookCategory" asp-action="Update" asp-route-id="@item.Id">Update Book Category</a>
                        </td>
                        <td>
                            <a class=" text-dark btn btn-danger" asp-area="" asp-controller="BookCategory" asp-action="Delete" asp-route-id="@item.Id">Delete Book Category</a>
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BookRegistrationSystem/Views/BookCategory/Update.cshtml
@model BookCategory
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<div class="container mt-5">
    <form method="post"asp-action="update" enctype="multipart/form-data">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.Name" class="control-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mt-3 text-end">
                <a class="btn btn-info" asp-area="" asp-controller="BookCategory" asp-action="Index"><i class="bi bi-arrow-return-left"></i> Back to main</a>
                <input type="submit" value="Update" class="btn btn-warning" />
            </div>
        </div>
    </form>

</div>