BookRegistrationSystem/Models/AuthorContact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Models
{
    public class AuthorContact:Base
    {
        [Required]
        [DisplayName("Telefon nömrəsi")]
        public string ContactNumber { get; set; }
        [Required]
        [DisplayName("Ünvanı")]
        public string Address { get; set; }
        [Required]
        [DisplayName("Yazıçı id")]
        public string AuthorId { get; set; }
     
    }
}

BookRegistrationSystem/Controllers/AuthorContactController.cs
using BookRegistrationSystem.Data;
using BookRegistrationSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BookRegistrationSystem.Controllers
{
    public class AuthorContactController : Controller
    {
        private readonly BookDbContext _bookDbContext;
        public AuthorContactController(BookDbContext bookDbContext)
        {
            _bookDbContext = bookDbContext;
        }

        public IActionResult Index()
        {
           var listItems = _bookDbContext.AuthorContacts.ToList();
            return View(listItems);
        }
        [HttpPost]
        public IActionResult Create(AuthorContact authorContact)
        {
                _bookDbContext.AuthorContacts.Add(authorContact);
                _bookDbContext.SaveChanges();
                TempData["SuccesMesssage"] = "AuthorContact added succecfully";
                return RedirectToAction("Index");
         
        }
        [HttpGet]
        public IActionResult Create()
        {
         
            return View();
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id != null)
            {
                var authorContact = _bookDbContext.AuthorContacts.Find(id);
                return View(authorContact);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Update(AuthorContact authorContact)
        {
                _bookDbContext.AuthorContacts.Update(authorContact);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                 var authorContact = _bookDbContext.AuthorContacts.Find(id);
                return View(authorContact);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Delete(AuthorContact authorContact)
        {
            if (ModelState.IsValid)
            {
                _bookDbContext.AuthorContacts.Remove(authorContact);
                _bookDbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(authorContact);
        }
    }
}

BookRegistrationSystem/Views/AuthorContact/Create.cshtml
@model AuthorContact
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<div class="container mt-5">
    <form method="post" asp-action="create">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.ContactNumber" class="control-label"></label>
                    <input asp-for="@Model.ContactNumber" class="form-control" />
                    <span asp-validation-for="@Model.ContactNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.Address" class="control-label"></label>
                    <input asp-for="@Model.Address" class="form-control" />
                    <span asp-validation-for="@Model.Address" class="text-danger"></span>
                </div>
            </div>

            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.AuthorId" class="control-label"></label>
                    <input asp-for="@Model.AuthorId" class="form-control" />
                    <span asp-validation-for="@Model.AuthorId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mt-3 text-end">
                <a class="btn btn-info" asp-area="" asp-controller="AuthorContact" asp-action="Index"><i class="bi bi-arrow-return-left"></i> Back to main</a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </form>

</div>

BookRegistrationSystem/Views/AuthorContact/Delete.cshtml
@model AuthorContact
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<div class="container mt-5">
    <form method="post" asp-action="delete">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-4">
                <div class="form-group">
                    <input  type="hidden" asp-for="Id"/>
                    <label asp-for="ContactNumber" class="control-label"></label>
                    <input readonly asp-for="ContactNumber" class="form-control" />
                    <span asp-validation-for="ContactNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input readonly asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>

            <div class="col-4">
                <div class="form-group">
                    <label asp-for="AuthorId" class="control-label"></label>
                    <input readonly asp-for="AuthorId" class="form-control" />
                    <span asp-validation-for="AuthorId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mt-3 text-end">
                <a class="btn btn-info" asp-area="" asp-controller="AuthorContact" asp-action="Index"><i class="bi bi-arrow-return-left"></i> Back to main</a>
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </div>
    </form>

</div>

BookRegistrationSystem/Views/AuthorContact/Index.cshtml
@model List<AuthorContact>
@{
    ViewData["Title"] = "Index";
}

<partial name="_ShowResult" />

<div class="page-container mt-5">
    <div class="row">
        <div class="col-6 text-end">
            <a class=" text-dark btn btn-success" asp-area="" asp-controller="AuthorContact" asp-action="Create">Create Author Contact</a>
        </div>
    </div>
    <div class="row">
        <table class="table table-hover table-bordered table-striped mt-5">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>ContactNumber</th>
                    <th>Address</th>
                    <th>AuthorId</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.ContactNumber</td>
                    <td>@item.Address</td>
                    <td>@item.AuthorId</td>
                    <td>
                        <a class=" text-dark btn btn-warning" asp-area="" asp-controller="AuthorContact" asp-action="Update" asp-route-id="@item.Id">Update Author Contact</a>
                    </td>
                    <td>
                        <a class=" text-dark btn btn-danger" asp-area="" asp-controller="AuthorContact" asp-action="Delete" asp-route-id="@item.Id">Delete Author Contact</a>
                    </td>

                </tr>
                }
            </tbody>
        </table>
    </div>

</div>

BookRegistrationSystem/Views/AuthorContact/Update.cshtml
@model AuthorContact
@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<div class="container mt-5">
    <form method="post" asp-action="update">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.ContactNumber" class="control-label"></label>
                    <input asp-for="@Model.ContactNumber" class="form-control" />
                    <span asp-validation-for="@Model.ContactNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.Address" class="control-label"></label>
                    <input asp-for="@Model.Address" class="form-control" />
                    <span asp-validation-for="@Model.Address" class="text-danger"></span>
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label asp-for="@Model.AuthorId" class="control-label"></label>
                    <input asp-for="@Model.AuthorId" class="form-control" />
                    <span asp-validation-for="@Model.AuthorId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group mt-3 text-end">
                <a class="btn btn-info" asp-area="" asp-controller="AuthorContact" asp-action="Index"><i class="bi bi-arrow-return-left"></i> Back to main</a>
                <input type="submit" value="Update" class="btn btn-warning" />
            </div>

        </div>
    </form>

</div>